url: "https://shilyaeva.art"
title:
  en: Ekaterina Shilyaeva
  ru: Екатерина Шиляева
slogan:
  en: Watercolorist & graphic artist.
  ru: Акварель и графика.
email: mail@shilyaeva.art
include: [ "_pages", _pages/en/", "_pages/ru/" ]
